# Generated by Django 6.0.6 on 2026-06-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_conflicts', models.IntegerField(default=0, help_text='Hard constraint violations in the manually built timetable.')),
                ('manual_time_minutes', models.IntegerField(default=0, help_text='Estimated minutes to build the manual timetable.')),
                ('manual_sessions_scheduled', models.IntegerField(default=0, help_text='Sessions successfully placed in the manual timetable.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'Evaluation Baseline',
            },
        ),
    ]
